# Site settings
name: LESS OR MORE
email: huawen.yu@gmail.com
author: Wilson Huawen Yu
url: http://huawenyu.github.io
resume_site: http://huawenyu.github.io/Resume.md/
github: https://github.com/huawenyu
baseurl: ""
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: IT'S OUR WITS THAT MAKE US MEN.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: huawenyu
highlighter: Pygments

# Build settings
markdown: kramdown

github: [metadata]
kramdown:
    input: GFM
    hard_wrap: false
gems:
    - jekyll-sitemap
    - jekyll-coffeescript
    - jekyll-paginate

# GitHub Pages & Jekyll override the following settings in your _config.yml file, which you cannot change:
lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
    noscript: false
kramdown:
    math_engine: mathjax
#FB:
#  comments :
#    provider : duoshuo
#    duoshuo:
#        short_name : huawenyu
#    disqus :
#        short_name : huawenyu
#    # facebook :
#    #   appid : 123
#    #   num_posts: 5
#    #   width: 580
#    #   colorscheme: light
