# Site settings
name: LESS IS MORE
email: huawen.yu@gmail.com
author: Wilson Huawen Yu
url: http://huawenyu.github.io
resume_site: http://huawenyu.github.io/2012/12/18/Resume/
github: https://github.com/huawenyu
baseurl: ""
description: Everything should be made as simple as possible, but no simpler.
meta_description: blog, embedded linux, c, network security
motto: Keep it simple, stupid.
banner: Keep it simple, less is more!

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: huawenyu
#highlighter: Pygments

# Build settings

gems: ['jekyll-sitemap', 'jekyll-coffeescript', 'jekyll-paginate']

# GitHub Pages & Jekyll override the following settings in your _config.yml file, which you cannot change:
lsi: false
safe: true
source: ''
future: true
incremental: false
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge
    math_engine: mathjax
gist:
    noscript: false

collections:
  faqs:
    output: true
    permalink: /:collection/:path/
    title: FAQs

#FB:
#  comments :
#    provider : duoshuo
#    duoshuo:
#        short_name : huawenyu
#    disqus :
#        short_name : huawenyu
#    # facebook :
#    #   appid : 123
#    #   num_posts: 5
#    #   width: 580
#    #   colorscheme: light
